version: "3.9"

services:
  app:
    build:
      context: ./My_Docker
      dockerfile: Dockerfile
    ports:
      - "7178:80"
    depends_on:
      - db

  webapi:
    build:
      context: ./MyAPI
      dockerfile: Dockerfile
    ports:
      - "7209:80"
    depends_on:
      - db
    command: dotnet ef database update

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      MSSQL_SA_PASSWORD: "Mattrangmattroi1"
      ACCEPT_EULA: "Y"